# Generated by Django 3.2.7 on 2021-09-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210920_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Category',
            field=models.ManyToManyField(to='blog.Category', verbose_name='دسته بندی'),
        ),
    ]
